spring:
  application:
    name: notification-manager
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASSWORD:guest}
  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:1025}
    username: ${MAIL_USERNAME:""}
    password: ${MAIL_PASSWORD:""}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 8083

app:
  messaging:
    dead-letter:
      exchange: dead-letter-exchange
      binding-key: dead-letter
      queue: dead-letter-queue
    notifications:
      exchange: notifications-exchange
      notifications-binding-key: notifications
      queue: notifications-queue
  email:
    default-from: ${MAIL_FROM:no-reply@challenges.com}