spring:
  application:
    name: challenge-manager
  datasource:
    url: jdbc:postgresql://localhost:5432/multiplication-db
    username: multiplication-user
    password: secret
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
  jpa:
    show-sql: true
server:
  error:
    include-message: always
    include-binding-errors: always

app:
  challenge-generator:
    difficulty-levels:
      - level: easy
        min: 1
        max: 9
      - level: medium
        min: 11
        max: 99
      - level: hard
        min: 101
        max: 999
      - level: expert
        min: 1001
        max: 9999