spring:
  application:
    name: challenge-manager
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/challenge-manager-db}
    username: challenge-manager-user
    password: secret
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
  jpa:
    show-sql: true
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    publisher-confirm-type: CORRELATED
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    username: ${REDIS_USER:default}
    password: ${REDIS_PASSWORD}
server:
  error:
    include-message: always
    include-binding-errors: always

app:
  cors:
    allowed-origins: ${ALLOWED_ORIGINS:http://127.0.0.1:3000}
    allowed-methods: GET,POST,PUT,DELETE
    allowed-headers: Authorization,Content-Type,X-Requested-With,Accept,Origin,Access-Control-Request-Method,Access-Control-Request-Headers,Access-Control-Allow-Origin
  auth:
    secret: ${AUTH_SECRET:}
    expiration-time: "PT6H"
  challenge-generator:
    difficulty-levels:
      - level: easy
        min: 1
        max: 9
      - level: medium
        min: 11
        max: 99
      - level: hard
        min: 101
        max: 999
      - level: expert
        min: 1001
        max: 9999
  messaging:
    dead-letter:
      exchange: dead-letter-exchange
      routing-key: dead-letter
      queue: dead-letter-queue
    challenge:
      exchange: challenge-exchange
      challenge-correct-routing-key: challenge-solved.correct
      challenge-failed-routing-key: challenge-solved.incorrect