spring:
  application:
    name: multiplication
  datasource:
    url: jdbc:h2:mem:multiplication
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
server:
  error:
    include-message: always
    include-binding-errors: always

app:
  challenge-generator:
    min: 11
    max: 99