spring:
  application:
      name: gamification-manager
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/gamification-manager-db}
    username: gamification-manager-user
    password: secret
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
  jpa:
    show-sql: true
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    username: ${REDIS_USER:default}
    password: ${REDIS_PASSWORD}
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 10
          initial-interval: 1000
          multiplier: 4
          max-interval: 3600000
        default-requeue-rejected: false
server:
  port: 8082

app:
  cors:
    allowed-origins: ${ALLOWED_ORIGINS:http://127.0.0.1:3000}
    allowed-methods: GET,POST,PUT,DELETE
    allowed-headers: Authorization,Content-Type,X-Requested-With,Accept,Origin,Access-Control-Request-Method,Access-Control-Request-Headers,Access-Control-Allow-Origin
  difficulty-levels:
    - level: easy
      digits: 1
      score: 10
    - level: medium
      digits: 2
      score: 20
    - level: hard
      digits: 3
      score: 30
    - level: expert
      digits: 4
      score: 40
  badges:
    - badge-type: FIRST_WON
    - badge-type: BRONZE
      score_threshold: 100
    - badge-type: SILVER
      score_threshold: 250
    - badge-type: GOLD
      score_threshold: 500
    - badge-type: LUCKY_NUMBER
      lucky_number: 42
  leaderboard:
    key: leaderboard
    size: 10
  messaging:
    dead-letter:
      exchange: dead-letter-exchange
      routing-key: dead-letter
      queue: dead-letter-queue
    challenge:
      exchange: challenge-exchange
      challenge-correct-routing-key: challenge-solved.correct
      queue: challenge-solved.correct.queue
