spring:
  application:
      name: gamification-manager
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/gamification-manager-db}
    username: gamification-manager-user
    password: secret
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
  jpa:
    show-sql: true
server:
  port: 8082

app:
  cors:
    allowed-origins: ${ALLOWED_ORIGINS:http://127.0.0.1:3000}
    allowed-methods: GET,POST,PUT,DELETE
    allowed-headers: Authorization,Content-Type,X-Requested-With,Accept,Origin,Access-Control-Request-Method,Access-Control-Request-Headers,Access-Control-Allow-Origin
  difficulty-levels:
    - level: easy
      digits: 1
      score: 10
    - level: medium
      digits: 2
      score: 20
    - level: hard
      digits: 3
      score: 30
    - level: expert
      digits: 4
      score: 40
  badges:
    - badge-type: FIRST_WON
    - badge-type: BRONZE
      score_threshold: 100
    - badge-type: SILVER
      score_threshold: 250
    - badge-type: GOLD
      score_threshold: 500
    - badge-type: LUCKY_NUMBER
      lucky_number: 42
